app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('appuser.urls', 'appuser'), namespace='appuser')), 
    path('', include(('appPost.urls', 'appPost'), namespace='appPost')), 
    path('', include(('appchat.urls', 'appchat'), namespace='appchat')), 


]


if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appPost/urls.py
from django.urls import path

from .views import CreatePostView, DeletePostView, DetailPostView, create_post, editar_post, get_all_user_posts, get_posts


app_name = 'appPost'

urlpatterns = [
    path('', get_posts, name="menu"), 
    path('postear/', create_post, name='postear'),
    path('delete_post/<int:pk>/', DeletePostView.as_view(), name='delete_post'), 
    path('ver_posts/<int:pk>/', get_all_user_posts, name='ver_posts'), 
    path('detail_post/<int:pk>/', DetailPostView.as_view(), name='detail_post'), 
    path('editar_post/<int:pk>/', editar_post, name='editar_post'), 
]

appchat/urls.py
from django.urls import path

from .views import create_chatroom, enterRoom, chatRoom, ver_rooms

app_name = 'appchat'

urlpatterns = [
    path('room/<int:pk>', chatRoom, name='chatroom'), 
    path('enter_room/<int:pk>', enterRoom, name='enterRoom'),
    path('ver_rooms/', ver_rooms, name='ver_rooms'),
    path('create_chatroom/', create_chatroom, name='create_chatroom') 
    
]

appuser/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import DeleteUserView, DetailUserView, LoginUserView, RegisterUserView, UpdateUserView, editar_avatar, logout, subir_avatar
from appPost.views import get_all_user_posts

app_name = 'appuser'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'), 
    path('login/', LoginUserView.as_view(), name='login'),
    path('update_user/', UpdateUserView.as_view(), name='update_user'), 
    path('delete_user/', DeleteUserView.as_view(), name='delete_user'), 
    path('ver_perfil/', DetailUserView.as_view(), name='detail_user'), 

    path('logout/', logout, name='logout'),
    path('subir_avatar/', subir_avatar, name='subir_avatar'), 
    path('editar_avatar/', editar_avatar, name='editar_avatar'), 
    
    
] 

appchat/models.py
from django.db import models

from appuser.models import User

# Create your models here.
class Mensaje (models.Model): 
    mensaje = models.TextField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True, verbose_name='Enviado')

class ChatRoom (models.Model): 
    nombre = models.CharField(max_length=20)
    users  = models.ManyToManyField(User)
    mensajes = models.ManyToManyField(Mensaje, null=True, blank=True)

 

appchat/forms.py
from django import forms

from .models import ChatRoom, Mensaje

class ChatRoomForm(forms.ModelForm): 
    class Meta: 
        model= ChatRoom 
        fields =  ['nombre']
        widgets = {
            'users' : forms.HiddenInput(), 
            'mensajes' : forms.HiddenInput(),

        }
    

class MensajeForm(forms.ModelForm): 
    class Meta: 
        model = Mensaje 
        fields =  "__all__"
        widgets = {
            'user' : forms.HiddenInput(),
            'fecha' : forms.HiddenInput(),
        }
        
    
 

appchat/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, CreateView, DeleteView, ListView, UpdateView
from django.contrib.auth.decorators import login_required
from .forms import ChatRoomForm, MensajeForm
from .models import ChatRoom, Mensaje

# Create your views here.

class CreateMensajeView(CreateView): 
    model = Mensaje 
    form_class = MensajeForm
    fields = ('mensaje')
    template = './templates/appchat/mensaje_form.html'

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial


class DetailMensajeView(DetailView): 
    model = Mensaje
    template_name = './templates/appuser/mensaje.html'
    context_object_name = 'mensaje'


@login_required
def create_chatroom(request): 
    if request.method == 'POST' : 
        form = ChatRoomForm(request.POST) 

        if form.is_valid() : 
            chatroom = form.save()
            chatroom.users.add(request.user)
            chatroom.save()
            room = chatroom.nombre
            return redirect('appchat:chatroom', pk=chatroom.id)
            
    else: 
        form = ChatRoomForm()

    return render(request, './appchat/chatroom_form.html', {'form' : form})

def ver_rooms(request): 
    rooms = ChatRoom.objects.all()
    return render(request, './appchat/ver_rooms.html', {'rooms' : rooms})

def enterRoom (request): 
    form = ChatRoomForm(request.POST)
    
    if ChatRoom.objects.filter(nombre= form.fields['nombre']).exists():
        return redirect('room/' + form.fields['nombre'])
    else: 
        if form.is_valid(): 
            form.save()
        else: 
            form = ChatRoomForm() 

    return render(request, './appchat/enter_room.html', {'form' : form})


def chatRoom (request, pk): 
    room = get_object_or_404(ChatRoom, id=pk)
    return render(request, './appchat/chat_room.html', {'room' : room})


def enviarMensaje (request, room):
    chat = ChatRoom.objects.filter(nombre = room).values() 
    if request.method == 'POST': 
        form = MensajeForm(request.POST)

        if form.is_valid(): 
            chat.mensajes.append(form)
            chat.save()
            ##refresh auto 
        else: 
            form = MensajeForm()

    return render(request, './templates/appchat/chat_room.html', {'form' : form})

appchat/templates/appchat/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'appchat/style.css' %}">
</head>
<body>
    <nav>
        
        <a href="{% url 'appuser:register' %}">Crear Usuario</a>
        <a href="{% url 'appuser:login' %}">Iniciar Sesion</a>
        <a href="{% url 'appPost:postear' %}">Postear</a>
        <a href="{% url 'appuser:detail_user' %}">Ver perfil</a>
        <a href="{% url 'appchat:ver_rooms' %}">Ver rooms</a>

    </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

appchat/templates/appchat/chat_room.html
{% extends "appchat/base.html" %}

{% block content %}
{% if room %}
<div>
    <h1>{{room.nombre}}</h1>
    {% for m in room.mensajes %}
    <div>
    <p>{{m.mensaje}}</p>
    <h5>{{m.user}}</h5>
    <h5>{{m.fecha}}</h5>
    </div>
    {% endfor %}
</div>
{% else %}
<div><h1>No existe el chatroom</h1></div>
{% endif %}
{% endblock content %}

appchat/templates/appchat/chatroom_form.html
{% extends "appchat/base.html" %}
{% block content %}
<form  method="post">
    
    <fieldset>
        <legend>Escribe aqui</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Crear</button>

    </fieldset>

</form>
{% endblock content %}

appchat/templates/appchat/enter_room.html
{% extends "appchat/base.html" %}

{% block content %}
<form  method="post">
    
    <fieldset>
        <legend>Escribe aqui</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postear</button>
        <button type="reset">Borrar todo</button>

    </fieldset>

    {% for error in field.errors %} {{ error }} {% endfor %}

</form>
{% endblock content %} 

appchat/templates/appchat/mensaje_form.html
{% block content %}
<form  method="post">
    
    <fieldset>
        <legend>Escribe aqui</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postear</button>
        <button type="reset">Borrar todo</button>

    </fieldset>

</form>
{% endblock content %}

appchat/templates/appchat/ver_rooms.html
{% extends "appchat/base.html" %}
{% block content %}
<a href="{% url 'appchat:create_chatroom' %}"><button>Crear chatroom</button></a>
{% if  rooms %}
{% for r in rooms %}
<div class="contenedor">
    <h2 class="title">{{r.nombre}}</h2>
</div>
{% endfor %}
{% else %}
<div>
    <h1>No hay chatrooms disponibles</h1>
</div>
{% endif %}
{% endblock content %}