app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('appuser.urls', 'appuser'), namespace='appuser')), 
    path('', include(('appPost.urls', 'appPost'), namespace='appPost')), 
    path('', include(('appchat.urls', 'appchat'), namespace='appchat')), 


]


if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appPost/urls.py
from django.urls import path

from .views import CreatePostView, DeletePostView, DetailPostView, create_post, editar_post, get_all_user_posts, get_posts


app_name = 'appPost'

urlpatterns = [
    path('', get_posts, name="menu"), 
    path('postear/', create_post, name='postear'),
    path('delete_post/<int:pk>/', DeletePostView.as_view(), name='delete_post'), 
    path('ver_posts/<int:pk>/', get_all_user_posts, name='ver_posts'), 
    path('detail_post/<int:pk>/', DetailPostView.as_view(), name='detail_post'), 
    path('editar_post/<int:pk>/', editar_post, name='editar_post'), 
]

appchat/urls.py
from django.urls import path

from .views import create_chatroom, enterRoom, chatRoom, ver_rooms

app_name = 'appchat'

urlpatterns = [
    path('room/<int:pk>', chatRoom, name='chatroom'), 
    path('enter_room/<int:pk>', enterRoom, name='enterRoom'),
    path('ver_rooms/', ver_rooms, name='ver_rooms'),
    path('create_chatroom/', create_chatroom, name='create_chatroom') 
    
]

appuser/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import DeleteUserView, DetailUserView, LoginUserView, RegisterUserView, UpdateUserView, editar_avatar, logout, subir_avatar
from appPost.views import get_all_user_posts

app_name = 'appuser'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'), 
    path('login/', LoginUserView.as_view(), name='login'),
    path('update_user/', UpdateUserView.as_view(), name='update_user'), 
    path('delete_user/', DeleteUserView.as_view(), name='delete_user'), 
    path('ver_perfil/', DetailUserView.as_view(), name='detail_user'), 

    path('logout/', logout, name='logout'),
    path('subir_avatar/', subir_avatar, name='subir_avatar'), 
    path('editar_avatar/', editar_avatar, name='editar_avatar'), 
    
    
] 

appuser/models.py
from datetime import timezone
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', default='avatares/default-pfp.png')

appuser/forms.py
from django import forms 
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Avatar

class UserCreationForm(UserCreationForm): 
    class Meta: 
        model = User 
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email')
        
class UpdateUserForm (UserChangeForm):
    password = None
    class Meta: 
        model = User 
        fields = ('username', 'first_name', 'last_name', 'email')
           
class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['imagen']

appuser/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from .models import Avatar
from .forms import UpdateUserForm, UserCreationForm
from django.contrib.auth.models import User
from appPost.models import Post 
from django.views.generic import DetailView, CreateView, DeleteView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from .forms import AvatarForm
from django.contrib.auth import logout

# Create your views here.

class LoginUserView (LoginView) : 
    template = './appuser/login_user.html '

class RegisterUserView(CreateView): 
    model = User 
    form_class= UserCreationForm
    template = './appuser/user_form.html'
    success_url = reverse_lazy('appuser:subir_avatar')
    
class UpdateUserView(LoginRequiredMixin, UpdateView): 
    model = User 
    form_class= UpdateUserForm
    template = './templates/appuser/edit_user.html' 
    success_url = reverse_lazy('appuser:detail_user')

    def get_object(self, queryset=None):
        return self.request.user
   

class DeleteUserView(LoginRequiredMixin, DeleteView): 
    model = User 
    template = './auth/user_confirm_delete.html'
    success_url = reverse_lazy('appuser:login')

    def get_object(self, queryset=None):
        return self.request.user

class DetailUserView(LoginRequiredMixin, DetailView): 
    model = User
    template_name = './appuser/detail_user.html'
    context_object_name = 'user'

    def get_object(self, queryset=None):
        return self.request.user
    

def logout(request):
    request.session.flush()
    return redirect('appuser:register')

@login_required
def subir_avatar(request):
    if request.method == 'POST':
        avatar = request.user.avatar 

        form = AvatarForm(request.POST, request.FILES, instance=avatar)
        if form.is_valid():
            form.save()
            return redirect('appPost:menu')
    else:
        form = AvatarForm()
    return render(request, './appuser/subir_avatar.html', {'form': form})

@login_required
def editar_avatar (request): 
    if request.method == 'POST': 
        try: 
            avatar = request.user.avatar
        except Avatar.DoesNotExist: 
            avatar = None 
        
        if avatar: 
            form = AvatarForm(request.POST, request.FILES, instance=avatar)
        else: 
            form = AvatarForm(instance=avatar)

        if form.is_valid(): 
            avatar_instance = form.save(commit=False)
            avatar_instance.user = request.user 
            avatar_instance.save()
            return redirect('appuser:detail_user')
    else: 
        if hasattr(request.user, 'avatar'):
            form = AvatarForm(instance=request.user.avatar)
        else : 
            form = AvatarForm()

    return render (request, './appuser/editar_avatar.html', {'form' : form}) 


@receiver(post_save, sender=User)
def create_avatar_for_user(sender, instance, created, **kwargs):
    if created:
        Avatar.objects.create(user=instance)

            

appuser/templates/appuser/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'appuser/style.css' %}">
</head>
<body>

    <nav>
        <a href="{% url 'appuser:register' %}">Crear Usuario</a>
        <a href="{% url 'appuser:login' %}">Iniciar Sesion</a>
        <a href="{% url 'appPost:postear' %}">Postear</a>
        <a href="{% url 'appPost:menu' %}">Menu</a>
        <a href="{% url 'appuser:detail_user' %}">Ver perfil</a>
        <a href="{% url 'appchat:ver_rooms' %}">Ver rooms</a>
    </nav>

    {% block content %}
    {% endblock content %}
</body>
</html>

appuser/templates/appuser/detail_user.html
{% extends "appuser/base.html" %}

{% block content %}


<div class="contenedor">
    <img src="{{user.avatar.imagen.url}}" alt="">
    <h1 id="username">{{user.username}}</h1>
    <h2 id="nombre">Nombre: {{user.first_name}} {{user.last_name}}</h2>
    <h2 id="gmail">Gmail: {{user.email}}</h2>

    <a href="{% url 'appuser:update_user' %}"><button>Editar datos</button></a>
    <a href="{% url 'appuser:editar_avatar' %}"><button>Editar avatar</button></a>
    <a href="{% url 'appuser:delete_user' %}"><button>Eliminar</button></a>
    <a href="{% url 'appPost:ver_posts' pk=user.id %}"><button>Mis posts</button></a>
    <a href="{% url 'appuser:logout' %}"><button>Cerrar sesion</button></a>

</div>

{% endblock content %}

appuser/templates/appuser/edit_user.html
{% extends "appuser/base.html" %}

{% block content %}
<h1>Editar usuario</h1>
<form  method="post">
    
    {% csrf_token %}
    {{ form.as_p }}
    <img src="{{user.avatar.imagen.url}}" alt="">
    <a href="{% url 'appuser:editar_avatar' %}"><button>Editar avatar</button></a>
    <button type="submit">Guardar</button>
    <button type="reset">Cancelar</button>
    

</form>
{% endblock content %}

appuser/templates/appuser/editar_avatar.html
{% extends "appuser/base.html" %}

{% block content %}
  <h2>Subir Avatar</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <img src="{{user.avatar.imagen.url}}" alt="">
    <button type="submit">Cambiar</button>
    <a href="{% url 'appuser:update_user' %}"><button>Cancelar</button></a>
  </form>
{% endblock %}

appuser/templates/appuser/lista.html
{% extends "appuser/base.html" %}

{% block content %}
{% for user in users%}
<h1>{{user.user}}</h1>
<div>
    <h2>Nombre: {{user.nombre_completo}}</h2>
    <h2>Gmail: {{user.gmail}}</h2>
    <h2>Cumpleaños: {{user.fecha_nacimiento}}</h2>
    <p>Descripcion: {{user.descripcion}}</p>

    <button><a href="{% url 'appuser:update_user' pk=user.id %}"></a></button>
    <button><a href="{% url 'appuser:delete_user' pk=user.id %}"></a></button>

</div>
{% endfor %}
{% endblock content %}

appuser/templates/appuser/page.html
{% extends "appuser/base.html" %}

{% block content %}

{% for p in posts %}

<div>
    {{p.fecha}}
    {{p.descripcion}}
</div>

{% endfor %}

{% endblock content %}

appuser/templates/appuser/subir_avatar.html
{% extends "appuser/base.html" %}

{% block content %}
  <h2>Subir Avatar</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Subir</button>
  </form>
{% endblock %}