app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('appuser.urls', 'appuser'), namespace='appuser')), 
    path('', include(('appPost.urls', 'appPost'), namespace='appPost')), 
    path('', include(('appchat.urls', 'appchat'), namespace='appchat')), 


]


if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appPost/urls.py
from django.urls import path

from .views import CreatePostView, DeletePostView, DetailPostView, create_post, editar_post, get_all_user_posts, get_posts


app_name = 'appPost'

urlpatterns = [
    path('', get_posts, name="menu"), 
    path('postear/', create_post, name='postear'),
    path('delete_post/<int:pk>/', DeletePostView.as_view(), name='delete_post'), 
    path('ver_posts/<int:pk>/', get_all_user_posts, name='ver_posts'), 
    path('detail_post/<int:pk>/', DetailPostView.as_view(), name='detail_post'), 
    path('editar_post/<int:pk>/', editar_post, name='editar_post'), 
]

appchat/urls.py
from django.urls import path

from .views import create_chatroom, enterRoom, chatRoom, ver_rooms

app_name = 'appchat'

urlpatterns = [
    path('room/<int:pk>', chatRoom, name='chatroom'), 
    path('enter_room/<int:pk>', enterRoom, name='enterRoom'),
    path('ver_rooms/', ver_rooms, name='ver_rooms'),
    path('create_chatroom/', create_chatroom, name='create_chatroom') 
    
]

appuser/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import DeleteUserView, DetailUserView, LoginUserView, RegisterUserView, UpdateUserView, editar_avatar, logout, subir_avatar
from appPost.views import get_all_user_posts

app_name = 'appuser'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'), 
    path('login/', LoginUserView.as_view(), name='login'),
    path('update_user/', UpdateUserView.as_view(), name='update_user'), 
    path('delete_user/', DeleteUserView.as_view(), name='delete_user'), 
    path('ver_perfil/', DetailUserView.as_view(), name='detail_user'), 

    path('logout/', logout, name='logout'),
    path('subir_avatar/', subir_avatar, name='subir_avatar'), 
    path('editar_avatar/', editar_avatar, name='editar_avatar'), 
    
    
] 

appPost/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


# Create your models here.

class Post (models.Model): 
    fecha = models.DateTimeField(auto_now_add=True)
    titulo= models.CharField(max_length=20)
    texto = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='img-posts', default='')
    epigrafe = models.CharField(max_length=20, blank=True)

appPost/forms.py
from datetime import datetime, time
from django import forms

from .models import Post


class PostForm (forms.ModelForm): 
    class Meta: 
        model = Post 
        fields =  ['titulo', 'epigrafe', 'imagen', 'texto']

class UpdatePostForm (forms.ModelForm): 
    user = None 
    
    class Meta: 
        model = Post 
        fields =  ['titulo', 'epigrafe', 'imagen', 'texto']

appPost/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, DeleteView, ListView, UpdateView, TemplateView
from .forms import PostForm, UpdatePostForm
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here. 

class HomeView (LoginRequiredMixin, TemplateView): 
    template = './appPost/menu.html'
                
class CreatePostView (LoginRequiredMixin, CreateView): 
    model = Post
    form_class = PostForm
    template = './appPost/post_form.html'
    success_url = reverse_lazy('appPost:menu')

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial

class DeletePostView(LoginRequiredMixin, DeleteView): 
    model = Post 
    template_name= './auth/post_confirm_delete.html'
    success_url = reverse_lazy('appPost:menu')

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)
    

class DetailPostView(LoginRequiredMixin, DetailView): 
    model = Post
    template_name = './appPost/detail_post.html'
    context_object_name = 'post'    

@login_required   
def create_post (request): 
    if request.method == 'POST' : 
        form = PostForm(request.POST, request.FILES) 

        if form.is_valid() :  
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('appPost:menu')
            
    else: 
        form = PostForm()

    return render(request, './appPost/post_form.html', {'form' : form})

@login_required
def editar_post (request, pk): 
    post = get_object_or_404(Post, id=pk)

    if post.user != request.user: 
        redirect('appPost:menu')

    if request.method == 'POST': 
        form = UpdatePostForm(request.POST, request.FILES, instance=post)

        if form.is_valid(): 
            form.save()
            return redirect('appPost:detail_post', pk=post.id)
    else: 
        form = UpdatePostForm(instance=post)
    
    return render (request, './appPost/editar_post.html', {'form' : form}) 




def get_posts(request): 
    posts = Post.objects.all()
    return render(request, './appPost/listar_posts.html', {'posts' : posts})


def get_all_user_posts(request, pk): 
    posts = Post.objects.filter(user__id=pk).values()
    return render(request, './appPost/listar_posts.html', {'posts' : posts})

appPost/templates/appPost/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'appPost/style.css' %}">
</head>
<body>
    <nav>
        
        <a href="{% url 'appuser:register' %}">Crear Usuario</a>
        <a href="{% url 'appuser:login' %}">Iniciar Sesion</a>
        <a href="{% url 'appPost:postear' %}">Postear</a>
        <a href="{% url 'appPost:menu' %}">Menu</a>
        <a href="{% url 'appuser:detail_user' %}">Ver perfil</a>
        <a href="{% url 'appchat:ver_rooms' %}">Ver rooms</a>
        
    </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

appPost/templates/appPost/detail_post.html
{% extends "appPost/base.html" %}
{% block content %}
<div class="contenedor">
    <h2 class="title">{{post.titulo}}</h2>
    <p class="texto">{{post.texto}}</p>
    <p class="fecha">{{post.fecha}}</p>
    <img id="img" src="{{ post.imagen.url }}" alt="">
    <p>{{post.epigrafe}}</p>
    <img id="imagen-user" src="{{ post.user.avatar.imagen.url }}" alt=""><p class="user">{{post.user.username}}</p>

    
</div>
{% if post.user.id == request.user.id %}
<a href="{% url 'appPost:delete_post' post.id %}">Eliminar</a>
<a href="{% url 'appPost:editar_post' post.id %}">Editar</a>
{% endif %}

{% endblock content %}

appPost/templates/appPost/editar_post.html
{% extends "appPost/base.html" %}

{% block content %}
<h1>Editar post</h1>
<form  method="post">
    
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Guardar</button>
    <button type="reset">Cancelar</button>
    

</form>
{% endblock content %}

appPost/templates/appPost/listar_posts.html
{% extends "appPost/base.html" %}
{% block content %}
{% if posts %}
{% for p in posts %}
<div class="contenedor">
    <h2 class="title">{{p.titulo}}</h2> 
    <img id="img" src="{{ post.imagen.url }}" alt="">
    <img id="imagen-user" src="{{ p.user.avatar.imagen.url }}" alt=""><p class="user">{{p.user.username}}</p>

    
</div>
<a href="{% url 'appPost:detail_post' pk=p.id %}">Ver detalle</a>
{% endfor %}
{% else %}
<div>
    <h1>No hay posts </h1>
</div>
{% endif %}
{% endblock content %}

appPost/templates/appPost/menu.html
{% extends "appPost/listar_posts.html" %}

appPost/templates/appPost/post_form.html
{% extends "appPost/base.html" %}

{% block content %}
<form  method="POST"  enctype="multipart/form-data">
    
    <fieldset>
        <legend>Escribe aqui</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postear</button>
        <button type="reset">Borrar todo</button>

    </fieldset>

</form>
{% endblock content %}